### ISSUE TITLE
[Minor bug / Enhancement]

### ISSUE THREAD

**Issue by Darktilldawn** [Time6628/CatClearLag#1]
So I'm having a minor issue when I change the interval for clearing the "lag."
https://gyazo.com/2459cb0fef634fb917fb1d170ba84f57
I have the interval set to interval=60 for 60 minutes. Yet it will only send a warning at 3030 and 3060 seconds left, and not display another message before clearing all the ground items. 

I would really like to see this enhancement brought to CatClearLag as it would bring much more control and support over which entities it will clear, meaning able to target specific mobs from any forge mod. I run a Pixelmon server so clearing entities is a nice feature but i would like to be able to specify between pixelmon.animals.torchich and other mods I believe use the same styled entity names. Maybe specify the whitelist into other categories such as 

entity-whitelist=[
    "pixelmon:animal.lugia",
    "minecraft:skeleton"
]
item-whitelist=[
    "pixelmon:master_ball",
    "minecraft:diamond"
]

**Comment by Time6628** [comment]
Your numbers are wrong for the first one, as there are 3600 seconds in a hour. So if you wanted it 60 seconds before, it would be 3540.

The second part is coming in the next update.
