### ISSUE TITLE
Likely that there are problems with translation support (messages.conf)

### ISSUE THREAD

**Issue by ziceptor** [Time6628/CatClearLag#10]
"Warning Message" not translated. The output in the console/chat:

[13:56:01] [pool-3-thread-37/INFO]: [ClearLag] Ground items will be cleared in 30 seconds.
[13:56:26] [pool-3-thread-37/INFO]: [ClearLag] Ground items will be cleared in 5 seconds.
[13:56:31] [pool-3-thread-39/INFO]: [Дворник] 0 предметов расщеплено на молекулы. Приборка завершена!

[messages.conf](https://gist.github.com/ziceptor/f135b9fda0182b85fd59364b102f16fa)

**Comment by Time6628** [comment]
Can you upload the full log?

**Comment by ziceptor** [comment]
[latest.log](https://gist.github.com/ziceptor/ecf086a4c664a84e8ad48481414efdff) or another file?

**Comment by Time6628** [comment]
fml-server-latest please.

**Comment by ziceptor** [comment]
[fml-server-latest.log](https://gist.github.com/ziceptor/abcd2ef71979e44408afc3b4e655fc12)

**Comment by Time6628** [comment]
Looks like it didn't upload all the way.

**Comment by ziceptor** [comment]
"Clearing Items Message" works
"Warning Message" not works

**Comment by Time6628** [comment]
I got that, I need the log so I can see why it's not working properly.

**Comment by ziceptor** [comment]
In the reports there are no errors.

**Comment by ziceptor** [comment]
All messages in red.

**Comment by Time6628** [comment]
http://jenkins.timethecat.pw:8080/job/CatClearLag/15/

**Comment by ziceptor** [comment]
Now displays the rows correctly. But these lines are missing the prefix:
`Ground items will be cleared in 30 seconds.`
`Ground items will be cleared in 5 seconds.`

ps
Warns only about your plugin! "Usually, such a file is not loaded..."
https://blog.mozilla.org/security/2016/08/01/enhancing-download-protection-in-firefox/
