### ISSUE TITLE
ClearLag is preventing player from dropping item's

### ISSUE THREAD

**Issue by JoeSGT** [Time6628/CatClearLag#14]
Here are my version's
spongeforge-1.12.2-2555-7.0.0-BETA-2774 
CatClearLag-0.8.1
Forge: forge-1.12.2-14.23.1.2565

basically if you spawn entities example spawn pig's all around you
just make sure you have a lot 
and then get a stack of item's in your inventory example of stack of stone blocks
and try drop all around the entities, as you see you are prevent to drop item's
because there are a few entities
i had ran a clean test server with no other mods then the one's i listed above
this is a big issue with Forge mods

please fixed this and thanks you

**Comment by Time6628** [comment]
You need to change the limit of entities per chunk in your config.

**Comment by JoeSGT** [comment]
@Time6628  Sorry for the late reply but what setting in the config ?
and also what do you recommend ?


EDIT: never mind i edited the plugin and allow dropped item
