### ISSUE TITLE
NullPointerException: null

### ISSUE THREAD

**Issue by ziceptor** [Time6628/CatClearLag#15]
https://gist.github.com/ziceptor/b4adfae42f8ebec361a542b1909859a6

forge-1.12.2-14.23.1.2555-universal.jar
spongeforge-1.12.2-2555-7.0.0-BETA-2764.jar
CatClearLag-0.8.1.jar latest ore

**Comment by rouing** [comment]
I am getting the same error.

https://pastebin.com/ZfDrfayX
