### ISSUE TITLE
Doesn't teleport to correct coordinates

### ISSUE THREAD

**Issue by cj89898** [Time6628/CatClearLag#2]
When using /lc it doesn't teleport you to the correct coordinates. The blockray gets the location of the chunk
`Optional<BlockRayHit<World>> c = BlockRay.from(b).stopFilter(BlockRay.onlyAirFilter()).to(a.getPosition().sub(a.getX(), 1, a.getZ())).end();`

it should be
`Optional<BlockRayHit<World>> c = BlockRay.from(b).stopFilter(BlockRay.onlyAirFilter()).to(a.getPosition().sub(b.getX(), 1, b.getZ())).end()`

I believe. This is the conversation where we looked at the issue: https://pastebin.com/raw/Qv3yWHEd

**Comment by Time6628** [comment]
Will be fixed in the next update.
