### ISSUE TITLE
Whitelist command doesn't write to config

### ISSUE THREAD

**Issue by Mahavo** [Time6628/CatClearLag#23]
Hi great mod and love the new update! When i do /clwhitelist it doesn't write to the config so when the plugins reload they get deleted again. I can still add them manually and they work however i can't get the appliedenergistics:material to work which is the crystals. The seeds however work. 

Revelations 1.8
Spongeforge 3016

**Comment by FabioZumbi12** [comment]
Confirmed, is not saving to the config on use the command.

**Comment by Time6628** [comment]
The appliedenergistics "sub items" will never work with this plugin unless the author changes the way he does the items.

**Comment by FabioZumbi12** [comment]
But is not only with appliedenergistics. Is with any other minecraft or mod items, the problem is with command only.
