### ISSUE TITLE
Ignoring shulker boxes in whitelist

### ISSUE THREAD

**Issue by SnowBlitzz** [Time6628/CatClearLag#26]
It seems that it ignores shulkerboxes that are whitelisted and clears them anyway whether they have items inside or not. The other items in the list are fine.

Whitelist=[
“pixelmon:exp_all”,
“pixelmon:orb”,
“pixelmon:uno_orb”,
“pixelmon:dos_orb”,
“pixelmon:tres_orb”,
“pixelmon:red_chain”,
“pixelmon:master_ball”,
“pixelmon:park_ball”,
“pixelmon:rare_candy”,
“minecraft:emerald”,
“pixelmon:crystal”,
“pixelmon:stone_badge”,
“pixelmon:balance_badge”,
“pixelmon:dynamo_badge”,
“pixelmon:heat_badge”,
“pixelmon:wave_badge”,
“pixelmon:jet_badge”,
“pixelmon:psychic_badge”,
“minecraft:white_shulker_box”,
“minecraft:orange_shulker_box”,
“minecraft:magenta_shulker_box”,
“minecraft:light_blue_shulker_box”,
“minecraft:yellow_shulker_box”,
“minecraft:lime_shulker_box”,
“minecraft:pink_shulker_box”,
“minecraft:gray_shulker_box”,
“minecraft:silver_shulker_box”,
“minecraft:cyan_shulker_box”,
“minecraft:purple_shulker_box”,
“minecraft:blue_shulker_box”,
“minecraft:brown_shulker_box”,
“minecraft:green_shulker_box”,
“minecraft:red_shulker_box”,
“minecraft:black_shulker_box”
]

**Comment by Wubsy** [comment]
Okay but why are you not whitelisting "minecraft:shulker_box"

**Comment by SnowBlitzz** [comment]
Because that's not their item ID. You can check it by doing ctrl+h and hovering over the item, or type /iteminfo with nucleus. I've tried putting minecraft:shulker_box there as well but it will still clear it.
