### ISSUE TITLE
Error Null

### ISSUE THREAD

**Issue by pinguino132** [Time6628/CatClearLag#29]
Hello, when i try to run any command from the plugin an error comes up "Error occurred while executing command: null"

The console output:

03.08 15:10:08 [Server] INFO java.lang.NullPointerException: null
03.08 15:10:08 [Server] INFO at me.time6628.clag.sponge.commands.subcommands.removeentities.RemoveXPCommand.execute(RemoveXPCommand.java:19) ~[RemoveXPCommand.class:?]
03.08 15:10:08 [Server] INFO at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:255) ~[ChildCommandElementExecutor.class:1.12.2-2705-7.1.0-BETA-3358]
03.08 15:10:08 [Server] INFO at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-2705-7.1.0-BETA-3358]
03.08 15:10:08 [Server] INFO at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:341) ~[SimpleDispatcher.class:1.12.2-2705-7.1.0-BETA-3358]
03.08 15:10:08 [Server] INFO at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:329) [SpongeCommandManager.class:1.12.2-2705-7.1.0-BETA-3358]
03.08 15:10:08 [Server] INFO at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]
03.08 15:10:08 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:958) [pa.class:?]
03.08 15:10:08 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:937) [pa.class:?]
03.08 15:10:08 [Server] INFO at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
03.08 15:10:08 [Server] INFO at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
03.08 15:10:08 [Server] INFO at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:92) [PacketUtil.class:1.12.2-2705-7.1.0-BETA-3358]
03.08 15:10:08 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zld000(SourceFile:539) [hv$1.class:?]
03.08 15:10:08 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
03.08 15:10:08 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_40]
03.08 15:10:08 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_40]
03.08 15:10:08 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
03.08 15:10:08 [Server] INFO at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:293) [SpongeImplHooks.class:1.12.2-2705-7.1.0-BETA-3358]
03.08 15:10:08 [Server] INFO at net.minecraft.server.MinecraftServer.redirect$onRun$zji000(MinecraftServer.java:3963) [MinecraftServer.class:?]
03.08 15:10:08 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
03.08 15:10:08 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
03.08 15:10:08 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
03.08 15:10:08 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
03.08 15:10:08 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]

I'm using spongeforge 1.12.2-2705-7.1.0-BETA-3358

**Comment by Time6628** [comment]
Could you try this version for me?
[CatClearLag-0.8.3.zip](https://github.com/Time6628/CatClearLag/files/2258387/CatClearLag-0.8.3.zip)

**Comment by pinguino132** [comment]
Of course, i will test it and come back !

**Comment by pinguino132** [comment]
Just tested it and got the same error, i dont know if it is related but the config and messages files are empty

03.08 15:46:41 [Server] Server thread/ERROR [Sponge]: Error occurred while executing command 're items' for source EntityPlayerMP['Pinguino132'/220, l='world', x=-199.30, y=120.00, z=137.53]: null
03.08 15:46:41 [Server] INFO java.lang.NullPointerException: null
03.08 15:46:41 [Server] INFO at me.time6628.clag.sponge.Messages.getPrefix(Messages.java:12) ~[Messages.class:?]
03.08 15:46:41 [Server] INFO at me.time6628.clag.sponge.commands.subcommands.removeentities.RemoveGItemsCommand.execute(RemoveGItemsCommand.java:20) ~[RemoveGItemsCommand.class:?]
03.08 15:46:41 [Server] INFO at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:255) ~[ChildCommandElementExecutor.class:1.12.2-2705-7.1.0-BETA-3358]
03.08 15:46:41 [Server] INFO at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-2705-7.1.0-BETA-3358]
03.08 15:46:41 [Server] INFO at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:341) ~[SimpleDispatcher.class:1.12.2-2705-7.1.0-BETA-3358]
03.08 15:46:41 [Server] INFO at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:329) [SpongeCommandManager.class:1.12.2-2705-7.1.0-BETA-3358]
03.08 15:46:41 [Server] INFO at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]
03.08 15:46:41 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:958) [pa.class:?]
03.08 15:46:41 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:937) [pa.class:?]
03.08 15:46:41 [Server] INFO at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
03.08 15:46:41 [Server] INFO at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
03.08 15:46:41 [Server] INFO at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:92) [PacketUtil.class:1.12.2-2705-7.1.0-BETA-3358]
03.08 15:46:41 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zld000(SourceFile:539) [hv$1.class:?]
03.08 15:46:41 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
03.08 15:46:41 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_40]
03.08 15:46:41 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_40]
03.08 15:46:41 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
03.08 15:46:41 [Server] INFO at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:293) [SpongeImplHooks.class:1.12.2-2705-7.1.0-BETA-3358]
03.08 15:46:41 [Server] INFO at net.minecraft.server.MinecraftServer.redirect$onRun$zji000(MinecraftServer.java:3963) [MinecraftServer.class:?]
03.08 15:46:41 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
03.08 15:46:41 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
03.08 15:46:41 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
03.08 15:46:41 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
03.08 15:46:41 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]

**Comment by Time6628** [comment]
Yea, try the recommended version of sponge. They broke something in the newer versions.

**Comment by pinguino132** [comment]
Okie! I will try using it, thank you  :D

**Comment by pinguino132** [comment]
Changed to recommended 3361 and it worked as it should.
