### ISSUE TITLE
Items added to whitelist still being cleared

### ISSUE THREAD

**Issue by Varitek3rulz3** [Time6628/CatClearLag#3]
Hi, it doesnt appear to allow me to add modded items to the whitelist, is this intentional or just a feature that isnt possible? Or am i doing something wrong, im running a sponge server with catclearlag-0.7

**Comment by Time6628** [comment]
Run /cwl while holding the item.

**Comment by Varitek3rulz3** [comment]
I did that, and tried to manually add them, and after a server restart it still removes them, to be specific, its the ae seeds used to grow different quartz, i wanted to add them bc they arent supposed to despawn, anyway, so it might have issues with the nbt? idrk but thanks for replying so quickly :D

**Comment by Time6628** [comment]
Yea, it's probably the nbt. Try adding them at every stage, because I think the ID changes.

**Comment by Varitek3rulz3** [comment]
ok ill try that next and let you know, thanks again.

**Comment by Varitek3rulz3** [comment]
ok so tried that, also tried re-installing the plugin bc why not, still clears modded items, not vanilla though. Not a huge deal but wanted to update you so youd know.

**Comment by fusionmc-evilscoop** [comment]
This is a huge deal....
its hitting appliedenergistics2:crystal_seed which makes growing crystals for AE2 near impossible...as you have to throw into water for between 8 mins and 8 hours to grow them

**Comment by Time6628** [comment]
Then pick them up before it clears, or use growth accelerators.

**Comment by fusionmc-evilscoop** [comment]
im not dictating how users play on the server, thats their choice, if they want to watch a seed for 8 hours let them.....this is obv a bug, and if it affects 1 item its likly to affect more.....
Im now more interested in your obv refusal to look into the bug....is it just lazyness, or do you really not give a damn about your userbase ?

**Comment by Time6628** [comment]
AE2 uses damages to the seed's id, sponge and minecraft itself no longer support this. The only way around this would be to remove the data from every item it checked to see if it was whitelisted and then check it. Currently, it just matches the item id with the id stored in the config making it a bit faster than the other way. This is something to take up with the ae2 devs, as they shouldn't be used damage/subids for their items.
