### ISSUE TITLE
WarinigMsg and WarningMsgMins

### ISSUE THREAD

**Issue by Russia9** [Time6628/CatClearLag#33]
I have an issue with translation of warningMsgMins. Rename second @Setting please.
`
       @Setting("Warning Message")
        public String warningMsg = "&cGround items will be cleared in &f%d seconds.";
        @Setting("Warning Message")
        public String warningMsgMins = "&cGround items will be cleared in &f%d minutes &f%d seconds."; 
`

**Comment by Time6628** [comment]
Already been fixed in-dev.
