### ISSUE TITLE
Warning & Clear message format

### ISSUE THREAD

**Issue by squidflex** [Time6628/CatClearLag#35]
Thanks for creating this plugin, Time! It helps a lot on my server.
That said, the messages are nigh-spamming the chat/console - we're getting extra formatting on Warning & Clear messages after updating to version 0.9.0.
I looked for a guide or explanation on how to adjust the message configs, but I was unable to find anything. I did find the messages.conf file under config/catclearlag, but I am hesitant to change anything without a little more information.

**From the server log:**
13.12 10:17:44 [Server] pool-3-thread-260/INFO {color=dark_purple, extra=[{text=[ClearLag] }], text=}{arguments={seconds={optional=false}}, closeArg=}, openArg={, options={closeArg=}, openArg={}, content={color=red, extra=[{text=Ground items will be cleared in }, {color=white, text={seconds}}, {text= seconds.}], text=}}
13.12 10:18:14 [Server] pool-3-thread-260/INFO {color=dark_purple, extra=[{text=[ClearLag] }], text=}{closeArg=}, content={extra=[{text=[ClearLag] }, {color=white, text={count}}, {text= items have been cleared.}], color=red, text=}, openArg={, arguments={count={optional=false}}, options={closeArg=}, openArg={}}

**In-game:** 
Only the "Ground items will be cleared in 1 minute 0 seconds" warning has any color applied. The prefix on that message and all the subsequent messages look like plain-text argument lists. 

Here's a screenshot:
![2018-12-13_10 29 43](https://user-images.githubusercontent.com/30320565/49949270-3c630400-fec3-11e8-871d-39671a11e5b0.png)

Any help would be greatly appreciated.
Thanks!

**Comment by Time6628** [comment]
Have you generated your configs?

**Comment by squidflex** [comment]
I'm guessing not. How would I do that?
I was using CatClearLag 0.8.3 without any issues on the same server...

**Comment by Time6628** [comment]
Delete the config, restart server.

**Comment by squidflex** [comment]
Duh! I was definitely over-thinking that. Recreating the configs did the trick. 
Thanks for help and thanks again for the plugin!
