### ISSUE TITLE
checks.put(Type.NAMED  .... does not include entityWhitelist at end

### ISSUE THREAD

**Issue by Bucky420** [Time6628/CatClearLag#37]
checks.put(Type.NAMED, notAPlayer().and(entity -> !entity.get(DisplayNameData.class).isPresent()));
should have **.and(entityWhitelist)** at the end? as i checked this out when i ran the command for name tags but found it ignored the whitelist

**Comment by Time6628** [comment]
It's meant to be used in conjunction with other flags, so /re -an will remove all entities, except the ones with names.

**Comment by HHServers** [comment]
This doesn't happen ^ whitelisted entities are removed regardless
