### ISSUE TITLE
Suggestion | Plural & Singular Messages

### ISSUE THREAD

**Issue by CrypticDivide** [Time6628/CatClearLag#38]
Instead of always having minutes and seconds, implement a way for messages to automatically be converted to singular form when there is only one **minute** or one **second**.

**Comment by LokeYourC3PH** [comment]
Or maybe let us disable them, I find them a little obnoxious actually.

**Comment by Time6628** [comment]
@LokeYourLord just remove all the values from the warnings part of the config.

**Comment by CrypticDivide** [comment]
Why was this closed? The original issue was never addressed.

**Comment by Time6628** [comment]
It has been done in-dev.

**Comment by CrypticDivide** [comment]
Ok, thank you for clarifying.

**Comment by LokeYourC3PH** [comment]
> 
> 
> It has been done in-dev.

I have tried that, I deleted the 540, 570 in that file, it still displays messages unfortunately :(
If I make it empty, it just comes back after reboot.

**Comment by LokeYourC3PH** [comment]
@Time6628 ^

**Comment by Time6628** [comment]
`Warnings=[]`
