### ISSUE TITLE
CatClearLag giving null error and not running.

### ISSUE THREAD

**Issue by X-Niter** [Time6628/CatClearLag#42]
Server thread/ERROR [Sponge]: Error occurred while executing command 'catclearlag:unloadchunks' for source EntityPlayerMP['Nova_Enginetics'/8720, l='Nova Enginetics', x=175.55, y=64.00, z=203.89]: null
02.07 13:17:07 [Server] INFO java.lang.NullPointerException: null
02.07 13:17:07 [Server] INFO at me.time6628.clag.sponge.commands.UnloadChunksCommand.execute(UnloadChunksCommand.java:19) ~[UnloadChunksCommand.class:?]
02.07 13:17:07 [Server] INFO at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-2825-7.1.6]
02.07 13:17:07 [Server] INFO at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:340) ~[SimpleDispatcher.class:1.12.2-2825-7.1.6]
02.07 13:17:07 [Server] INFO at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:337) [SpongeCommandManager.class:1.12.2-2825-7.1.6]
02.07 13:17:07 [Server] INFO at net.minecraft.command.ServerCommandManager.executeCommand(SourceFile:1156) [dh.class:?]
02.07 13:17:07 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.handleSlashCommand(NetHandlerPlayServer.java:960) [pa.class:?]
02.07 13:17:07 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.processChatMessage(NetHandlerPlayServer.java:939) [pa.class:?]
02.07 13:17:07 [Server] INFO at net.minecraft.network.play.client.CPacketChatMessage.processPacket(SourceFile:37) [la.class:?]
02.07 13:17:07 [Server] INFO at net.minecraft.network.play.client.CPacketChatMessage.processPacket(SourceFile:9) [la.class:?]
02.07 13:17:07 [Server] INFO at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193) [PacketPhaseUtil.class:1.12.2-2825-7.1.6]
02.07 13:17:07 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlk000(SourceFile:539) [hv$1.class:?]
02.07 13:17:07 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
02.07 13:17:07 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_201]
02.07 13:17:07 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_201]
02.07 13:17:07 [Server] INFO at net.minecraft.util.Util.runTask(SourceFile:529) [h.class:?]
02.07 13:17:07 [Server] INFO at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:307) [SpongeImplHooks.class:1.12.2-2825-7.1.6]
02.07 13:17:07 [Server] INFO at net.minecraft.server.MinecraftServer.redirect$onRun$zjo000(MinecraftServer.java:3970) [MinecraftServer.class:?]
02.07 13:17:07 [Server] INFO at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
02.07 13:17:07 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
02.07 13:17:07 [Server] INFO at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
02.07 13:17:07 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
02.07 13:17:07 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]

**Comment by Time6628** [comment]
Update.

**Comment by X-Niter** [comment]
To 0.9.0 for sponge 7.2.0?

**Comment by Time6628** [comment]
Sure, just not super old version like you are using now.

**Comment by X-Niter** [comment]
0.8.3 was what i was using. Will update it.

**Comment by X-Niter** [comment]
Looks like the same issue is still persistent.
I am going to assume that the reason is because i had the whitelist with an item that had something like 
appliedenergistics:seed:1200 and catclearlag does not use the :1200 information so i removed those. Am restarting server now to see if that was the issue.
