### ISSUE TITLE
Adding specific exceptions by other plugins

### ISSUE THREAD

**Issue by randombyte-developer** [Time6628/CatClearLag#5]
I am in the process of creating a plugin that spawns uncollectable items. CatClearLag would remove these entities. I suggest adding a method for custom checks that can be added by other plugins. This would give the plugins control over the clearing process.

**Comment by Time6628** [comment]
👍

**Comment by Time6628** [comment]
Began working on a service that you will be able to use though the sponge permission manager,
https://github.com/Time6628/CatClearLag/commit/d478198434391ad6d09e1419df342bd01f37dc07
if there are any suggestions or requests please let me know.

**Comment by randombyte-developer** [comment]
You didn't seem to add the actual service to git.

**Comment by Time6628** [comment]
It's added now.

**Comment by randombyte-developer** [comment]
Thanks!
