### ISSUE TITLE
Console Spam, possible to fix it ?

### ISSUE THREAD

**Issue by AiMLESS2k** [Time6628/CatClearLag#50]
CatClearLag Version: 0.9.0
Sponge-Forge Version: spongeforge-1.12.2-2838-7.1.7-RC3928

My console gets really hard spammed with the same message : https://pastebin.com/nX7juQn0

Is there any way to fix it ?

**Comment by Time6628** [comment]
Already fixed

**Comment by DJmanito** [comment]
The same problem, but I didn't find the fix on GitHub or spongepower ore
When can this problem be solved

**Comment by GMous** [comment]
Same issue.
CatClearLag Version: 0.9.0
Sponge-Forge Version: 1.12.2-2838-7.1.7-RC3906
