### ISSUE TITLE
Option To Disable Chat Warnings

### ISSUE THREAD

**Issue by thewickening** [Time6628/CatClearLag#57]
I love the bossbar feature which I would prefer to be the only thing that pops up with warnings etc.

Can you add an option to disable chat notifications?

**Comment by Time6628** [comment]
no

**Comment by CDAGaming** [comment]
Care to give a reason why? It's a bit inconsistent to have chat notifications when the bossbar gives more then enough info...

**Comment by Time6628** [comment]
no
