### ISSUE TITLE
[Suggestion] Config option to disable boss bar and sound

### ISSUE THREAD

**Issue by NLBlacky** [Time6628/CatClearLag#59]
We've been using this wonderful plugin for nearly 2 years now. Recently we've decided to move to the latest recommended Sponge version, but this sadly caused some issues with version 0.9.0 (event error on clearlag execution, countdown and manual running the command worked fine). 

We decided to move to version 0.9.4 but were forced to disable it shortly after due to the amount of complains from our community. The last version has a boss bar and sound at each warning which is very annoying and cannot be disabled. Since I want to use CatClearLag again as soon as we can, we would like to ask to have a config option to disable the bossbar and/or warning sounds.

**Comment by Time6628** [comment]
Turn down your voice volume client side to disable the noise.

**Comment by NLBlacky** [comment]
Thank you for your quick response. We're however not going to recommend everyone in our community to turn down their voice volume. I assume it is not that difficult to add a simple config option to disable the boss bar or sound? 

I'm giving this as a suggestion as I assume more servers might have their players complain about it so I thought it might be a nice feature you could add. I guess we'll just need to make a custom version of your plugin then.

**Comment by Time6628** [comment]
https://www.curseforge.com/minecraft/mc-mods/catclearlag/files/2927141
