### ISSUE TITLE
laggychunks NoSuchMethodError

### ISSUE THREAD

**Issue by ziceptor** [Time6628/CatClearLag#6]
/laggychunks entities and other
https://gist.github.com/ziceptor/6f677738441a6fb2e5ab68d3dabd6712

**Comment by Time6628** [comment]
It looks like those methods were removed, from the SpongeCommon but is still in the API. I will look this further.

**Comment by Time6628** [comment]
This should fix it http://jenkins.timethecat.pw:8080/job/CatClearLag/lastSuccessfulBuild/

**Comment by ziceptor** [comment]
Crash Report Unable to create injector  https://gist.github.com/ziceptor/06dfd1df1123723dfe63d6103b27ed40

**Comment by Time6628** [comment]
Should be fixed now http://jenkins.timethecat.pw:8080/job/CatClearLag/12/
