### ISSUE TITLE
Sound config not working

### ISSUE THREAD

**Issue by NLBlacky** [Time6628/CatClearLag#60]
Sounds are still played after disabling it in the config.

![image](https://user-images.githubusercontent.com/42154364/79046549-ebc3fe00-7c11-11ea-8234-78ae0170ed4f.png)

I do want to say that I appreciate the work you've done to add this to the configs.

**Comment by Time6628** [comment]
Fixed in this version https://www.curseforge.com/minecraft/mc-mods/catclearlag/files/2927183
