### ISSUE TITLE
Option to blacklist instead of whitelist

### ISSUE THREAD

**Issue by MadAlchemist** [Time6628/CatClearLag#63]
Why there is no option (or no documentation about this option) to remove only listed items? Because most lag is caused by cobblestone, gravel, etc. dropped on the floor in huge quantities while mining ores, but drop from dead players or mobs doesn't have enough quantity to cause lag, and can be left to despawn in vanilla way (wich grants player at least 5 minutes to find and recover loot) or picked up by some player. It would be perfect to have an option to clear only those laggy unneeded drops from mining, instead of making players very frequently lose everything and hate you and your plugin so much that everything around the player starts to decay from so much hate. And I am sure it's not too difficult to make option to choose wether list is blacklist or whitelist.

**Comment by Time6628** [comment]
Use live time.
