### ISSUE TITLE
Could not pass ChangeInventoryEvent$Pickup$Pre$Impl Error

### ISSUE THREAD

**Issue by Corcustos** [Time6628/CatClearLag#66]
I'm getting [this](https://pastebin.com/ziYPfnxT) error thrown into console whenever I pickup an item that wasn't dropped by myself. Happens to both inventories dropped by chests when broken or loot dropped by mobs.

Versions:
CatClearLag 0.9.5.1
SpongeForge 7.2.1
Forge 2847

**Comment by Time6628** [comment]
Disable live time.
