### ISSUE TITLE
Stop the removal of nametagged mobs

### ISSUE THREAD

**Issue by Whazaaaaa** [Time6628/CatClearLag#7]
As of right now the clearlag also removes mobs with a nametag. Is there a way to stop these nametagged mobs from being removed by clearlag?

If not suggestion to put it in ^^

Thanks.

**Comment by Time6628** [comment]
There currently isn't, but it will be added soon.

**Comment by RogueRaiden** [comment]
How about the ability to only remove some but not all of an animal in an area?

**Comment by rouing** [comment]
If the mob is nametagged, it gets set as persistent. It should be easy to check for such things.

**Comment by Rsslone** [comment]
Almost a year since that "soon". Is this still in the works or?
