### ISSUE TITLE
NullPointerException: null

### ISSUE THREAD

**Issue by ziceptor** [Time6628/CatClearLag#9]
forge-1.12.2-14.23.0.2486-universal.jar
spongeforge-1.12.2-2486-7.0.0-BETA-2645.jar
CatClearLag-0.8.1.jar

https://gist.github.com/ziceptor/9fb4456ca9e2bf5cdf695c6d081460e0

**Comment by Time6628** [comment]
http://jenkins.timethecat.pw:8080/job/CatClearLag/lastSuccessfulBuild/artifact/build/libs/CatClearLag-0.8.1.jar

**Comment by ziceptor** [comment]
The same.
https://gist.github.com/ziceptor/b3d6a3afab45b7c6690fbc15df8bc6c6

**Comment by Time6628** [comment]
http://jenkins.timethecat.pw:8080/job/CatClearLag/14/

**Comment by ziceptor** [comment]
Thank you!
